//
// Created by brout_m on 26/05/17.
//

#ifndef REPLIES_H_
# define REPLIES_H_

#include "types.h"

enum e_replies
{
  RPL_NOTOPIC,
  RPL_WELCOME,
  ERR_NOSUCHNICK,
  ERR_NOSUCHSERVER,
  ERR_NOSUCHCHANNEL,
  ERR_CANNOTSENDTOCHAN,
  ERR_TOOMANYCHANNELS,
  ERR_WASNOSUCHNICK,
  ERR_TOOMANYTARGETS,
  ERR_NOORIGINS,
  ERR_NORECIPIENT,
  ERR_NOTEXTTOSEND,
  ERR_NOTOPLEVEL,
  ERR_WILDTOPLEVEL,
  ERR_UNKOWNCOMMAND,
  ERR_NOMOTD,
  ERR_NOADMININFO,
  ERR_FILEERROR,
  ERR_NONICKNAMEGIVEN,
  ERR_ERRONEUSNICKNAME,
  ERR_NICKNAMEINUSE,
  ERR_NICKCOLLISION,
  ERR_USERNOTINCHANNEL,
  ERR_NOTONCHANNEL,
  ERR_USERONCHANNEL,
  ERR_NOLOGIN,
  ERR_SUMMONDISABLED,
  ERR_USERSDISABLED,
  ERR_NOTREGISTERED,
  ERR_NEEDMOREPARAMS,
  ERR_ALREADYREGISTRED,
  ERR_NOPERMFORHOST,
  ERR_PASSWDMISMATCH,
  ERR_YOUREBANNEDCREEP,
  ERR_KEYSET,
  ERR_CHANNELISFULL,
  ERR_UNKNOWNMODE,
  ERR_INVITEONLYCHAN,
  ERR_BANNEDFROMCHAN,
  ERR_BADCHANNELKEY,
  ERR_NOPRIVILEGES,
  ERR_CHANOPRIVSNEEDED,
  ERR_CANTKILLSERVER,
  ERR_NOOPERHOST,
  ERR_UMODEUNKNOWNFLAG,
  ERR_USERSDONTMATCH,
  ERR_END
};

extern char const *replies[ERR_END];
int needmoreparams(t_server *srv, Socket sock, char *line);
int reply(t_server *srv, Socket sock, char *const fmt, ...);

#endif /* !MYIRC_REPLIES_H */
